"""initial schema

Revision ID: 27782fc34930
Revises: 
Create Date: 2026-05-25 16:31:00.712399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27782fc34930'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pg_trgm is required for the GIN index on employee.name
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_initial_password', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.String(length=20), nullable=False),
    sa.Column('action', sa.Enum('LOGIN', 'LOGIN_FAIL', 'LOGOUT', 'CREATE', 'UPDATE', 'DELETE', 'DOWNLOAD', 'BATCH_RUN', name='audit_action_enum'), nullable=False),
    sa.Column('target_table', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_actor_ts', 'audit_log', ['actor', 'created_at'], unique=False)
    op.create_index('idx_audit_target', 'audit_log', ['target_table', 'target_id'], unique=False)
    op.create_table('department',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='dept_status_enum'), server_default='ACTIVE', nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('department_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('target_id', sa.String(length=20), nullable=False),
    sa.Column('change_type', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='change_type_enum'), nullable=False),
    sa.Column('before_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_by', sa.String(length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dept_history_target', 'department_history', ['target_id', 'changed_at'], unique=False)
    op.create_table('employee_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('target_id', sa.String(length=6), nullable=False),
    sa.Column('change_type', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='change_type_enum'), nullable=False),
    sa.Column('before_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_by', sa.String(length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_employee_history_target', 'employee_history', ['target_id', 'changed_at'], unique=False)
    op.create_table('employee_staging',
    sa.Column('emp_no', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('dept_code', sa.String(length=20), nullable=False),
    sa.Column('team_code', sa.String(length=20), nullable=True),
    sa.Column('rank', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('emp_no')
    )
    op.create_table('meeting_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('change_type', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='change_type_enum'), nullable=False),
    sa.Column('before_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_by', sa.String(length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_meeting_history_target', 'meeting_history', ['target_id', 'changed_at'], unique=False)
    op.create_table('meeting_room_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('change_type', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='change_type_enum'), nullable=False),
    sa.Column('before_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_by', sa.String(length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_room_history_target', 'meeting_room_history', ['target_id', 'changed_at'], unique=False)
    op.create_table('message_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sender', sa.String(length=20), nullable=False),
    sa.Column('recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('ref_type', sa.String(length=20), nullable=True),
    sa.Column('ref_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('SENT', 'FAILED', 'MOCK', name='message_status_enum'), server_default='MOCK', nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_equipment_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('change_type', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='change_type_enum'), nullable=False),
    sa.Column('before_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_by', sa.String(length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_equip_history_target', 'room_equipment_history', ['target_id', 'changed_at'], unique=False)
    op.create_table('team_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('target_id', sa.String(length=20), nullable=False),
    sa.Column('change_type', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='change_type_enum'), nullable=False),
    sa.Column('before_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_by', sa.String(length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_team_history_target', 'team_history', ['target_id', 'changed_at'], unique=False)
    op.create_table('used_token',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_table('meeting_room',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('NORMAL', 'TEMP_CLOSED', 'CLOSED', name='room_status_enum'), server_default='NORMAL', nullable=False),
    sa.Column('dept_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['dept_code'], ['department.code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('team',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dept_code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='team_status_enum'), server_default='ACTIVE', nullable=False),
    sa.ForeignKeyConstraint(['dept_code'], ['department.code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('employee',
    sa.Column('emp_no', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('dept_code', sa.String(length=20), nullable=False),
    sa.Column('team_code', sa.String(length=20), nullable=True),
    sa.Column('rank', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'RETIRED', name='employee_status_enum'), server_default='ACTIVE', nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_room_manager', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_initial_password', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('login_fail_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dept_code'], ['department.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_code'], ['team.code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('emp_no')
    )
    op.create_index('idx_employee_name', 'employee', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('idx_employee_status', 'employee', ['status'], unique=False, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('room_equipment',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('room_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint('quantity >= 1', name='ck_room_equipment_quantity'),
    sa.ForeignKeyConstraint(['room_id'], ['meeting_room.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'name', name='uq_room_equipment_name')
    )
    op.create_table('meeting',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('room_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', name='meeting_status_enum'), server_default='SCHEDULED', nullable=False),
    sa.Column('dept_code', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['employee.emp_no'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dept_code'], ['department.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['room_id'], ['meeting_room.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_meeting_dept', 'meeting', ['dept_code'], unique=False)
    op.create_index('idx_meeting_room_date', 'meeting', ['room_id', 'date', 'status'], unique=False, postgresql_where=sa.text("status != 'CANCELLED'"))
    op.create_index('idx_meeting_status_date', 'meeting', ['status', 'date'], unique=False)
    op.create_table('meeting_attendee',
    sa.Column('meeting_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('emp_no', sa.String(length=6), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['emp_no'], ['employee.emp_no'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meeting_id', 'emp_no')
    )
    op.create_index('idx_attendee_employee', 'meeting_attendee', ['emp_no'], unique=False)
    op.create_index('idx_attendee_meeting', 'meeting_attendee', ['meeting_id'], unique=False)
    op.create_table('meeting_file',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('meeting_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_by', sa.String(length=6), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['employee.emp_no'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_file')
    op.drop_index('idx_attendee_meeting', table_name='meeting_attendee')
    op.drop_index('idx_attendee_employee', table_name='meeting_attendee')
    op.drop_table('meeting_attendee')
    op.drop_index('idx_meeting_status_date', table_name='meeting')
    op.drop_index('idx_meeting_room_date', table_name='meeting', postgresql_where=sa.text("status != 'CANCELLED'"))
    op.drop_index('idx_meeting_dept', table_name='meeting')
    op.drop_table('meeting')
    op.drop_table('room_equipment')
    op.drop_index('idx_employee_status', table_name='employee', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index('idx_employee_name', table_name='employee', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_table('employee')
    op.drop_table('team')
    op.drop_table('meeting_room')
    op.drop_table('used_token')
    op.drop_index('idx_team_history_target', table_name='team_history')
    op.drop_table('team_history')
    op.drop_index('idx_equip_history_target', table_name='room_equipment_history')
    op.drop_table('room_equipment_history')
    op.drop_table('message_log')
    op.drop_index('idx_room_history_target', table_name='meeting_room_history')
    op.drop_table('meeting_room_history')
    op.drop_index('idx_meeting_history_target', table_name='meeting_history')
    op.drop_table('meeting_history')
    op.drop_table('employee_staging')
    op.drop_index('idx_employee_history_target', table_name='employee_history')
    op.drop_table('employee_history')
    op.drop_index('idx_dept_history_target', table_name='department_history')
    op.drop_table('department_history')
    op.drop_table('department')
    op.drop_index('idx_audit_target', table_name='audit_log')
    op.drop_index('idx_audit_actor_ts', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('admin_account')
    # Drop PostgreSQL native ENUM types
    sa.Enum(name='meeting_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='room_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='employee_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='team_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='dept_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='change_type_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='audit_action_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='message_status_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
